name: 'Holon Runtime'
description: 'Run a Holon execution unit to resolve an issue'
inputs:
  image:
    description: 'The base toolchain image to use'
    required: false
    default: 'golang:1.22'
  anthropic_api_key:
    description: 'Anthropic API Key (or ANTHROPIC_AUTH_TOKEN)'
    required: true
  anthropic_base_url:
    description: 'Anthropic Base URL'
    required: false
    default: 'https://api.anthropic.com'
  github_token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
  workspace:
    description: 'Path to workspace'
    required: false
    default: '.'
  out_dir:
    description: 'Path to output directory'
    required: false
    default: './holon-output'
  holonbot_broker_url:
    description: 'URL of the Holonbot Token Broker'
    required: false
    default: 'https://holon-one.vercel.app/api/exchange-token'
  log_level:
    description: 'Log level for CI visibility (debug, info, progress, minimal)'
    required: false
    default: 'progress'

outputs:
  token:
    description: 'The GitHub token used (either Holonbot token or input github_token)'
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Get Holonbot Token
      id: get_token
      shell: bash
      run: |
        if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
          echo "Fetching OIDC token from GitHub Actions runtime..."
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          
          if [ -n "$OIDC_TOKEN" ] && [ "$OIDC_TOKEN" != "null" ]; then
            echo "Sending OIDC token to broker: ${{ inputs.holonbot_broker_url }}"
            RESPONSE=$(curl -s -X POST "${{ inputs.holonbot_broker_url }}" \
              -H "Authorization: Bearer $OIDC_TOKEN" \
              -H "Content-Type: application/json")
            echo "Broker response: $RESPONSE"
            
            BOT_TOKEN=$(echo $RESPONSE | jq -r '.token // empty')
            
            if [ -n "$BOT_TOKEN" ]; then
              echo "Successfully obtained Holonbot token."
              echo "token=$BOT_TOKEN" >> $GITHUB_OUTPUT
              exit 0
            else
              ERROR=$(echo $RESPONSE | jq -r '.error // "Unknown error"')
              MSG=$(echo $RESPONSE | jq -r '.message // "No message provided"')
              echo "::warning title=Holonbot Auth::Token exchange failed: $ERROR ($MSG). Falling back to providing github.token."
            fi
          else
            echo "::warning title=Holonbot Auth::Failed to fetch OIDC token. Ensure 'permissions: id-token: write' is set if you want to use Holonbot identity."
          fi
        else
          echo "Skipping token exchange: id-token permission not granted or holonbot_broker_url is empty."
        fi
        echo "token=${{ inputs.github_token }}" >> $GITHUB_OUTPUT

    - name: Run Holon
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        ANTHROPIC_BASE_URL: ${{ inputs.anthropic_base_url }}
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
      run: |
        AGENT_BUNDLE="${HOLON_AGENT_BUNDLE:-}"
        # Build holon and bundle if not present
        if [ ! -f bin/holon ]; then
          make build
        fi
        if [ -z "$AGENT_BUNDLE" ]; then
          echo "Building agent bundle..."
          (cd images/adapter-claude && npm run bundle)
          AGENT_BUNDLE=$(ls -t images/adapter-claude/dist/agent-bundles/*.tar.gz | head -n 1)
        fi

        # Extract issue info from event
        if [ -f "$GITHUB_EVENT_PATH" ]; then
          TITLE=$(jq -r '.issue.title // empty' "$GITHUB_EVENT_PATH")
          BODY=$(jq -r '.issue.body // empty' "$GITHUB_EVENT_PATH")

          if [ -n "$TITLE" ]; then
            GOAL="Issue Title: $TITLE\n\nIssue Description:\n$BODY"
            ./bin/holon run --goal "$GOAL" --image "${{ inputs.image }}" --agent-bundle "$AGENT_BUNDLE" --workspace "${{ inputs.workspace }}" --out "${{ inputs.out_dir }}" --log-level "${{ inputs.log_level }}"
          else
            echo "Not an issue event or title is empty."
            exit 1
          fi
        else
          echo "GITHUB_EVENT_PATH not found."
          exit 1
        fi
