name: 'Holon Runner'
description: 'Run a Holon agent execution to resolve an issue'
inputs:
  image:
    description: 'The base toolchain image to use'
    required: false
    default: 'golang:1.22'
  agent:
    description: 'Agent bundle reference (path to .tar.gz)'
    required: false
  anthropic_api_key:
    description: 'Anthropic API Key (or ANTHROPIC_AUTH_TOKEN)'
    required: true
  anthropic_base_url:
    description: 'Anthropic Base URL'
    required: false
    default: 'https://api.anthropic.com'
  github_token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
  workspace:
    description: 'Path to workspace'
    required: false
    default: '.'
  out_dir:
    description: 'Path to output directory'
    required: false
    default: './holon-output'
  context:
    description: 'Path to context directory'
    required: false
    default: ''
  holonbot_broker_url:
    description: 'URL of the Holonbot Token Broker'
    required: false
    default: 'https://holon-one.vercel.app/api/exchange-token'
  log_level:
    description: 'Log level for CI visibility (debug, info, progress, minimal)'
    required: false
    default: 'progress'
  mode:
    description: 'Execution mode: execute, pr-fix, plan, review (default: execute)'
    required: false
    default: 'execute'
  goal:
    description: 'Goal description (used when spec is not provided, takes precedence over issue event extraction)'
    required: false
    default: ''
  spec:
    description: 'Path to holon spec file (takes precedence over goal)'
    required: false
    default: ''
  role:
    description: 'Role to assume (e.g. developer, reviewer)'
    required: false
    default: ''

outputs:
  token:
    description: 'The GitHub token used (either Holonbot token or input github_token)'
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Get Holonbot Token
      id: get_token
      shell: bash
      run: |
        if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
          echo "Fetching OIDC token from GitHub Actions runtime..."
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          
          if [ -n "$OIDC_TOKEN" ] && [ "$OIDC_TOKEN" != "null" ]; then
            echo "Sending OIDC token to broker: ${{ inputs.holonbot_broker_url }}"
            RESPONSE=$(curl -s -X POST "${{ inputs.holonbot_broker_url }}" \
              -H "Authorization: Bearer $OIDC_TOKEN" \
              -H "Content-Type: application/json")
            echo "Broker response: $RESPONSE"
            
            BOT_TOKEN=$(echo $RESPONSE | jq -r '.token // empty')
            
            if [ -n "$BOT_TOKEN" ]; then
              echo "Successfully obtained Holonbot token."
              echo "token=$BOT_TOKEN" >> $GITHUB_OUTPUT
              exit 0
            else
              ERROR=$(echo $RESPONSE | jq -r '.error // "Unknown error"')
              MSG=$(echo $RESPONSE | jq -r '.message // "No message provided"')
              echo "::warning title=Holonbot Auth::Token exchange failed: $ERROR ($MSG). Falling back to providing github.token."
            fi
          else
            echo "::warning title=Holonbot Auth::Failed to fetch OIDC token. Ensure 'permissions: id-token: write' is set if you want to use Holonbot identity."
          fi
        else
          echo "Skipping token exchange: id-token permission not granted or holonbot_broker_url is empty."
        fi
        echo "token=${{ inputs.github_token }}" >> $GITHUB_OUTPUT

    - name: Run Holon
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        ANTHROPIC_BASE_URL: ${{ inputs.anthropic_base_url }}
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
      run: |
        AGENT_REF="${{ inputs.agent }}"
        if [ -z "$AGENT_REF" ]; then
          AGENT_REF="${HOLON_AGENT:-${HOLON_AGENT_BUNDLE:-}}"
        fi
        # Build holon and bundle if not present
        if [ ! -f bin/holon ]; then
          make build
        fi
        if [ -z "$AGENT_REF" ]; then
          echo "Building agent bundle..."
          (cd agents/claude && npm run bundle)
          AGENT_REF=$(ls -t agents/claude/dist/agent-bundles/*.tar.gz | head -n 1)
        fi

        # Build base command arguments
        CONTEXT_ARGS=()
        if [ -n "${{ inputs.context }}" ]; then
          CONTEXT_ARGS=(--context "${{ inputs.context }}")
        fi

        MODE_ARGS=(--mode "${{ inputs.mode }}")

        ROLE_ARGS=()
        if [ -n "${{ inputs.role }}" ]; then
          ROLE_ARGS=(--role "${{ inputs.role }}")
        fi

        # Determine goal: use explicit inputs, or extract from issue event
        if [ -n "${{ inputs.spec }}" ]; then
          # Spec mode - explicit spec file takes precedence
          echo "Using explicit spec file: ${{ inputs.spec }}"
          ./bin/holon run \
            --spec "${{ inputs.spec }}" \
            --image "${{ inputs.image }}" \
            --agent "$AGENT_REF" \
            --workspace "${{ inputs.workspace }}" \
            --out "${{ inputs.out_dir }}" \
            "${MODE_ARGS[@]}" \
            "${ROLE_ARGS[@]}" \
            "${CONTEXT_ARGS[@]}" \
            --log-level "${{ inputs.log_level }}"
        elif [ -n "${{ inputs.goal }}" ]; then
          # Goal mode - explicit goal takes precedence
          echo "Using explicit goal: ${{ inputs.goal }}"
          ./bin/holon run \
            --goal "${{ inputs.goal }}" \
            --image "${{ inputs.image }}" \
            --agent "$AGENT_REF" \
            --workspace "${{ inputs.workspace }}" \
            --out "${{ inputs.out_dir }}" \
            "${MODE_ARGS[@]}" \
            "${ROLE_ARGS[@]}" \
            "${CONTEXT_ARGS[@]}" \
            --log-level "${{ inputs.log_level }}"
        elif [ -f "$GITHUB_EVENT_PATH" ]; then
          # Fall back to extracting from issue event (backward compatibility)
          TITLE=$(jq -r '.issue.title // empty' "$GITHUB_EVENT_PATH")
          BODY=$(jq -r '.issue.body // empty' "$GITHUB_EVENT_PATH")

          if [ -n "$TITLE" ]; then
            GOAL="Issue Title: $TITLE\n\nIssue Description:\n$BODY"
            echo "Extracting goal from issue event: $TITLE"
            ./bin/holon run \
              --goal "$GOAL" \
              --image "${{ inputs.image }}" \
              --agent "$AGENT_REF" \
              --workspace "${{ inputs.workspace }}" \
              --out "${{ inputs.out_dir }}" \
              "${MODE_ARGS[@]}" \
              "${ROLE_ARGS[@]}" \
              "${CONTEXT_ARGS[@]}" \
              --log-level "${{ inputs.log_level }}"
          else
            echo "Error: No spec, goal, or issue event title available."
            exit 1
          fi
        else
          echo "Error: No spec, goal provided, and GITHUB_EVENT_PATH not found."
          exit 1
        fi
